version: '3.9'

services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tour
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  tour:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tour
    command: bash -c "python /app/src/infra/manage.py migrate && python /app/src/infra/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env-docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  postgres_data:
