version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - tour-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  tour:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python /app/src/manage.py runserver 0.0.0.0:8080"
    env_file:
      - ./.env
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  tour-data:
