version: '3.9'

services:
  database:
    image: postgres:14.1-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tour
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  tour:
    build: .
      # context: .
      # dockerfile: Dockerfile
    # command: bash -c "python /app/src/manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env-docker
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - database

volumes:
  postgres_data:
