# Generated by Django 4.2.1 on 2023-05-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0002_company_department_employee_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(
                help_text='Numero do CNPJ',
                max_length=14,
                unique=True,
                verbose_name='CNPJ',
            ),
        ),
    ]
