# Generated by Django 4.2.1 on 2023-05-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
